site_name: Resident Evil Outbreak Docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
- toc:
      permalink: true
- pymdownx.arithmatex:
      generic: true
- pymdownx.tabbed:
      alternate_style: true     
- abbr
- attr_list
- tables
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.snippets
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
- Home: index.md
- Game Data:
  - game data/index.md
  - Characters: game data/characters.md
  - Items: game data/items.md
  - Rooms: game data/rooms.md
  - Animations: game data/animations.md
- Mechanics:
  - mechanics/index.md
  - Virus Gauge: mechanics/virusGauge.md
  - Character Speed: mechanics/characterSpeed.md
- 3D:
  - 3D/index.md
  - Model file formats: 3D/models.md
- Sound:
  - sound/index.md
- Textures:
  - textures/index.md

plugins:
  - search

extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js